---
title: "ODA"
author: "Oscar Morales"
date: '2024-09-11'
output:
  html_document: default
  pdf_document: default
---

# Manual para Replicar {.tabset .tabset-fade}

## Cargar Librerias
```{r,  echo = TRUE, results = 'hide', warning=FALSE, message=FALSE}
library(tidyverse) # manejo de dataframes
library(reshape2)  # para tranfromar data de long a wide
library(WDI)       # libreria para acceder a metadata de banco mundial
library(readxl)    # leer archivos de excel
library(readr)     # leer archivos csv
library(visdat)    # visualizacion de datos como graficos
library(plotly)    # graficos
library(plm)       # modelos lineales para datos panel
library(lmtest)    # Pruebas de modelos lineales
library(broom)     # Manejar tablas
library(knitr)     # Imprimir tablas
library(car)       # test y utilidades para modelos
```

## Cargar Datos {.tabset .tabset-fade}

### Paises
```{r}
country_class <- read_excel("Data/CLASS.xlsx", sheet = "List of economies")
country_class <- country_class %>% 
  filter(!is.na(Region), !is.na(`Income group`)) %>%
  merge(WDI_data$country, by.x='Code', by.y ='iso3c') %>% 
  select(Code, iso2c, country, Region, `Income group`) %>%
  rename(iso3c = `Code`, region = Region, income = `Income group`)
```

### V-DEM
```{r}
v_dem_vars <- c("Electoral democracy index", "Exclusion by Gender index")
V_DEM <- read_excel("Data/VDEM-CORE.xlsx", sheet = "Data")

V_DEM <- V_DEM %>%
  select(-3, -5, -6, -7, -8) %>% 
  filter(Indicator %in% v_dem_vars) %>% 
  rename(iso3c = `Economy ISO3`, country = `Economy Name`, indicator = Indicator) %>%
  melt(id.vars = c("iso3c", "country", "indicator"), variable.name = "year") %>%
  arrange(iso3c, indicator, year) %>%
  merge(country_class) %>%
  select(iso2c, indicator, year, value)

V_DEM$indicator[V_DEM$indicator == "Electoral democracy index"] <- "dem"
V_DEM$indicator[V_DEM$indicator == "Exclusion by Gender index"] <- "exc"
v_dem_vars <- c("dem", "exc")

```

### HDI
```{r}
hdi_vars <- c('hdi')
HDI <- read_csv("Data/datos_python_HDI.csv", 
                col_names = c('Code', 'iso2c', 'indicator', 'year', 'value'), 
                col_types = list(col_character(), 
                                 col_character(), 
                                 col_character(), 
                                 col_double(), 
                                 col_double()),
                na = 'None') %>% 
  filter(indicator %in% hdi_vars) %>%
  select(iso2c, indicator, year, value)
```

### WORLD BANK
```{r, warning=FALSE}
wb_vars <- c('ODA.GNI','ODA.ALL','ODA.PC','CC','GE','PV','RQ','RL','VA','GDP.PC','GDP.PPP','GROW','SAV')
WB <- data.frame(indicator = character(), iso2c = character(), year = double(), value = double())


for (indicator in wb_vars) {
  WB <- rbind(WB, read_csv(paste("Data/datos_python_", indicator, ".csv", sep =''), 
                           col_names = c('indicator', 'iso2c', 'year', 'value'),
                           col_types = list(col_character(), col_character(), col_double(), col_double()),
                           na = "None"))
}

WB <- WB %>% select(iso2c, indicator, year, value)
```

### CLIO-INFRA
```{r}
CLIO <- read_excel("Data/GlobalExtremePovertyDollaraDay_Compact.xlsx", sheet = "Data Long Format")

names(CLIO) <- c("ccode", "country", "year", "value")

CLIO[CLIO=="Cape Verde"] <- "Cabo Verde"
CLIO[CLIO=="Congo"] <- "Congo, Rep."
CLIO[CLIO=="Egypt"] <- "Egypt, Arab Rep."
CLIO[CLIO=="Iran"] <- "Iran, Islamic Rep."
CLIO[CLIO=="Kyrgyzstan"] <- "Kyrgyz Republic"
CLIO[CLIO=="Laos"] <- "Lao PDR"
CLIO[CLIO=="Macedonia"] <- "North Macedonia"
CLIO[CLIO=="Russia"] <- "Russian Federation"
CLIO[CLIO=="Slovakia"] <- "Slovak Republic"
CLIO[CLIO=="South Korea"] <- "Korea, Rep."
CLIO[CLIO=="Swaziland"] <- "Eswatini"
CLIO[CLIO=="Syria"] <- "Syrian Arab Republic"
CLIO[CLIO=="The Gambia"] <- "Gambia, The"
CLIO[CLIO=="Turkey"] <- "Turkiye"
CLIO[CLIO=="Venezuela"] <- "Venezuela, RB"
CLIO[CLIO=="Yemen"] <- "Yemen, Rep."

CLIO <- CLIO %>%
  merge(WDI_data$country, all.x = TRUE) %>%
  mutate(indicator = 'POV') %>%
  select(indicator, iso2c, year, value) %>%
  arrange(iso2c, year) %>%
  select(iso2c, indicator, year, value)
```

### OUR WORLD IN DATA
```{r, message=FALSE}
LIBERTIES <- read_csv("DATA/political-civil-liberties-index.csv") %>%
  filter(!is.na(Code)) %>%
  mutate(indicator = 'LIB') %>%
  merge(country_class, by.x = 'Code', by.y = 'iso3c') %>%
  select(iso2c, indicator, year, value)
```

## Manipular Datos

### Transformar datos a la estructura wide
```{r}
datos_paper <- rbind(WB, HDI, CLIO, LIBERTIES, V_DEM) %>%
  pivot_wider(names_from = indicator, values_from = value) %>%
  complete(iso2c, year)
```

### Definir Indice de Governanza
```{r}
datos_paper <- datos_paper %>% mutate(GOV = (CC + GE + PV + RQ + RL + VA) / 6)
```

### Definir variables Dicotomicas / clasificacion
```{r}
datos_paper <- datos_paper %>% mutate(GOV_high = case_when(is.na(GOV) ~ NA_real_, GOV >= 0 ~ 1, TRUE ~ 0))

dem_avg <- read_csv("Data/Electoral Democracy Index.csv")

datos_paper <- datos_paper %>% merge(dem_avg %>% select(1, 2), by.x = 'year', by.y = 'Year', all.x = TRUE) %>%
                mutate(dem_high = case_when(is.na(dem) ~ NA_real_, 
                                            is.na(`*World`) ~ NA_real_,
                                            dem >= `*World` ~ 1, 
                                            TRUE ~ 0)) %>% select(-`*World`)

exc_avg <- read_csv("Data/Exclusion by Gender.csv")

datos_paper <- datos_paper %>% merge(exc_avg %>% select(1, 2), by.x = 'year', by.y = 'Year', all.x = TRUE) %>%
                mutate(exc_high = case_when(is.na(exc) ~ NA_real_, 
                                            is.na(`*World`) ~ NA_real_,
                                            exc >= `*World` ~ 1, 
                                            TRUE ~ 0)) %>% select(-`*World`)

lib_avg <- read_csv("DATA/political-civil-liberties-index.csv") %>% filter(Code == 'OWID_WRL')

datos_paper <- datos_paper %>% merge(lib_avg %>% select(3, 4) %>% rename(WORLD = value), all.x = TRUE) %>%
                mutate(lib_high = case_when(is.na(LIB) ~ NA_real_, 
                                            is.na(WORLD) ~ NA_real_,
                                            LIB >= WORLD ~ 1, 
                                            TRUE ~ 0)) %>% select(-WORLD)

datos_paper <- datos_paper %>% merge(country_class %>% select(iso2c, region, income), all.x = TRUE) 

```


### Filtros
```{r, echo=FALSE}
# CC GE PC RQ RL VA no hay datos anuales antes de 2002 y no hay datos 2023
# fuera por no contar con muchos años en GOV
gov_delete_c <- c('CW','FO','GI','GL','IM','MI','JG','MC','MF','MP','NC','PF','SM','SS','SX','TC','TW','VE','VG')
# en dem y exc hay datos desde 1990
dem_delete_c <- c('BA','BZ','DM','FM','GD','KI','KZ','LC','ME','MH','MK','PS','SS','TM','TO','TV','VC','WS','XK')
exc_delete_c <- c('BA','BZ','DM','FM','GD','GN','KI','KZ','LC','ME','MH','MK','PS','SS','TM','TO','TV','VC','WS','XK')
# en hdi hay datos desde 1990
hdi_delete_c <- c('KP','XK','SO','MH','BT','SS','ER','GW','LB','TM','VU','PS','SR','ME','NG','GD','BA','CV','DM','ET','FM','GE','GQ','KI','KM','TD','TL','UZ','VC','AO','BF','LR','MG','SB','AZ','BY','DJ','MK','MV','RS','RW','WS')
# lib ademas de los filtros pasados
lib_delete_c <- c('YE')
# GDP.PC y GDP.PPP ademas de los demas filtros
gdp_delete_c <- c('AF','CD','CU','IR','MZ','SY')
ppp_delete_c <- c('AF','CD','CU','IR','MZ','SY','IQ')
# ODA.ALL
oda_delete_c <- c('ZA','KG','MD','TJ','AM')
opc_delete_c <- c('ZA','KG','MD','TJ','AM','LY','UA')
# usando hdi, lib, dem y exc
delete_c <- exc_delete_c %>% union(hdi_delete_c) %>% union(lib_delete_c) %>% union(ppp_delete_c) %>% union(opc_delete_c)

recuperar_c <- datos_paper %>% filter(year >= 1993, year <=2022, iso2c %in% delete_c) %>% group_by(iso2c) %>% 
  summarise(ODA.GNI_na = sum(is.na(ODA.GNI)),
            ODA.ALL_na = sum(is.na(ODA.ALL)),
            ODA.PC_na = sum(is.na(ODA.PC)),
            GDP.PC_na = sum(is.na(GDP.PC)),
            GDP.PPP_na = sum(is.na(GDP.PPP)),
            GROW_na = sum(is.na(GROW)),
            hdi_na = sum(is.na(hdi)),
            LIB_na = sum(is.na(LIB)),
            dem_na = sum(is.na(dem)),
            exc_na = sum(is.na(exc))
            ) %>%
  mutate(sum_na = ODA.GNI_na + ODA.ALL_na + ODA.PC_na + GDP.PC_na + GDP.PPP_na + GROW_na + hdi_na + LIB_na + dem_na + exc_na) %>%
  select(iso2c, sum_na) %>% arrange(sum_na) %>% filter(sum_na == 0) %>% .$iso2c

filtro_c <- delete_c %>% setdiff(recuperar_c) %>% sort()

first_y <- 1993
last_y <- 2022

country_class %>% filter(income != 'High income') %>% filter(!iso2c %in% filtro_c) %>% group_by(income) %>% summarise(countries = n())


# 131 paises
# 33 años
# 4323 registros

# 68 paises
# 33 años
# 2244 registros

# 71 paises
# 32 años
# 2272 registros

# 74 paises
# 31 años
# 2294 registros

#----------IDEAL
# 77 paises
# 30 años
# 2310 registros
#----------

# 78 paises
# 29 años
# 2262 registros

vis_dat(country_class %>% filter(income != 'High income') %>%
          merge(datos_paper) %>% select(iso2c, year, region, income, ODA.GNI, ODA.ALL, ODA.PC, GDP.PC, GDP.PPP, 
                                        GROW, hdi, LIB, lib_high, dem, dem_high, exc, exc_high) %>% 
          arrange(iso2c, year) %>%
          filter(year >= first_y, year <= last_y, !iso2c %in% filtro_c))

cat("#### Filtro de países\n")
filtro_c
cat("#### Primer año\n")
first_y
cat("#### Ultimo año\n")
last_y
```

## Modelos  {.tabset .tabset-fade}
```{r}
# 1993 - 2022
datos_model <- country_class %>% filter(income != 'High income') %>% merge(datos_paper) %>%
  select(iso2c, year, region, income, ODA.GNI, ODA.ALL, ODA.PC, GDP.PC, GDP.PPP, 
         GROW, hdi, LIB, lib_high, dem, dem_high, exc, exc_high) %>%
  arrange(iso2c, year) %>% filter(year >= first_y, year <= last_y, !iso2c %in% filtro_c)
```

```{r}
# 2002 - 2022
# datos_model <- country_class %>% filter(!income %in% c('High income', 'Upper middle income')) %>% merge(datos_paper) %>% 
#   select(iso2c, year, ODA.ALL, ODA.PC, GDP.PC, GROW, hdi, GOV, GOV_high) %>% 
#   arrange(iso2c, year) %>% filter(year >= 2002, year <= last_y,
#                                   !iso2c %in% c('SS', 'BT', 'ER', 'GW', 'KP', 'LB', 'NG', 'PS', 'SO', 'VU', 'FM', 'KI', 'SB', 'SY'))
```

```{r}
formulas <- list(
  # list(name = 'modelo1', vd = 'hdi', vi = c('ODA.GNI','GDP.PPP','GROW','LIB','dem','exc'), vint = c()),
  # list(name = 'modelo2', vd = 'hdi', vi = c('ODA.GNI','GDP.PC' ,'GROW','LIB','dem','exc'), vint = c()),
  # list(name = 'modelo3', vd = 'hdi', vi = c('ODA.GNI','GDP.PC' ,'GROW','LIB','dem'),       vint = c()),
  # list(name = 'modelo4', vd = 'hdi', vi = c('GDP.PC' ,'GROW', 'dem', 'LIB'), vint = c('ODA.GNI*dem_high')),
  # list(name = 'modelo5', vd = 'hdi', vi = c('GDP.PC' ,'GROW', 'dem'), vint = c('ODA.GNI*dem_high')),
  # list(name = 'modelo6', vd = 'hdi', vi = c('GDP.PC' ,'GROW', 'exc'), vint = c('ODA.GNI*exc_high')),
  # list(name = 'Original', vd = 'hdi', vi = c('GDP.PC' ,'GOV'), vint = c('ODA.PC*GOV_high')),
  # list(name = 'modelo7', vd = 'hdi', vi = c('GDP.PC' ,'GROW', 'dem'), vint = c('ODA.PC*dem_high')),
  # list(name = 'modelo8', vd = 'hdi', vi = c('GDP.PC' ,'GROW', 'exc'), vint = c('ODA.PC*exc_high')),
  # list(name = 'modelo9', vd = 'hdi', vi = c('GDP.PC' ,'GROW', 'LIB'), vint = c('ODA.PC*lib_high')),
  # list(name = 'modelo10', vd = 'GDP.PC', vi = c('ODA.PC', 'hdi' ,'GROW', 'LIB', 'dem', 'exc'), vint = c()),
  # list(name = 'modelo11', vd = 'GDP.PC', vi = c('ODA.PC', 'hdi' ,'GROW', 'dem', 'exc'), vint = c()),
  # list(name = 'modelo12', vd = 'GDP.PC', vi = c('hdi' ,'GROW', 'dem'), vint = c('ODA.PC*dem_high')),
  # list(name = 'modelo13', vd = 'GDP.PC', vi = c('hdi' ,'GROW', 'exc'), vint = c('ODA.PC*exc_high')),
  # list(name = 'gdp modelo14', vd = 'GDP.PC', vi = c('ODA.PC' ,'hdi','GROW', 'dem'), vint = c(), vf = c('factor(region)', 'factor(income)')),
  # list(name = 'gdp modelo15', vd = 'GDP.PC', vi = c('ODA.PC' ,'hdi','GROW', 'exc'), vint = c(), vf = c('factor(region)', 'factor(income)')),
  #list(name = 'gdp modelo16', vd = 'GDP.PC', vi = c('ODA.PC' ,'GROW', 'dem'), vint = c(), vf = c('factor(region)', 'factor(income)')),
  list(name = 'gdp modelo17', vd = 'GDP.PC', vi = c('ODA.PC' ,'GROW', 'exc'), vint = c(), vf = c('factor(region)', 'factor(income)')),
  # list(name = 'gdp modelo18', vd = 'GDP.PC', vi = c('ODA.PC' ,'GROW', 'LIB'), vint = c(), vf = c('factor(region)', 'factor(income)')),
  #list(name = 'hdi modelo14', vd = 'hdi', vi = c('ODA.PC', 'GDP.PC', 'dem'), vint = c(), vf = c('factor(region)', 'factor(income)')),
  #list(name = 'hdi modelo15', vd = 'hdi', vi = c('ODA.PC', 'GDP.PC', 'exc'), vint = c(), vf = c()),
  # list(name = 'hdi modelo19', vd = 'hdi', vi = c('ODA.PC', 'GDP.PC', 'LIB'), vint = c(), vf = c()),
  list(name = 'hdi modelo20', vd = 'hdi', vi = c('GDP.PC', 'exc'), vint = c('ODA.PC*exc_high'), vf = c()),
  #list(name = 'hdi modelo21', vd = 'hdi', vi = c('GDP.PC', 'dem'), vint = c('ODA.PC*dem_high'), vf = c()),
  #list(name = 'hdi modelo22', vd = 'hdi', vi = c('GDP.PC', 'exc'), vint = c('ODA.PC*exc_high'), vf = c('factor(region)', 'factor(income)'))
  list(name = 'hdi modelo20', vd = 'GDP.PC', vi = c('GROW', 'exc'), vint = c('ODA.PC*exc_high'), vf = c())
  )
```


```{r, results='asis', echo=FALSE}
for (f in formulas){
  form <- paste(f$vd, '~', paste(c(f$vint, f$vi, f$vf), collapse = ' + '))
  formula = as.formula(form)
  
  cat("### ", f$name, "\n")
  
  cat("#### ", gsub("*", " x ", form, fixed = TRUE), " {.tabset .tabset-fade}\n")
  
  cat("##### OLS\n")
  model_ols <- plm(formula, data=datos_model, index = c('iso2c', 'year'), model = "pooling")
  print(kable(tidy(model_ols) %>% mutate(significant = case_when(p.value < 0.001 ~ '***', 
                                                  p.value < 0.01  ~ '**',
                                                  p.value < 0.05  ~ '*',
                                                  p.value < 0.1   ~ '.',
                                                  TRUE            ~ ''))))
    cat("* R-Squared: ",r.squared(model_ols)," \n")
  
    cat("* Breusch-Pagan LM test - Cross Sectional Dependance \n")
    print(kable(tidy(pcdtest(model_ols, test = c("lm")))))
    
    cat("* Pesaran CD test - Cross Sectional Dependance \n")
    print(kable(tidy(pcdtest(model_ols, test = c("cd")))))
    
    cat("* Serial Correlation\n")
    print(kable(tidy(pbgtest(model_ols))))
    
    cat("* Robust covariance matrix estimation \n")
    print(kable(tidy(coeftest(model_ols, vcovHC(model_ols, method = 'white1'))) %>% 
                  mutate(significant = case_when(p.value < 0.001 ~ '***', 
                                                  p.value < 0.01  ~ '**',
                                                  p.value < 0.05  ~ '*',
                                                  p.value < 0.1   ~ '.',
                                                  TRUE            ~ ''))))
  
  cat("##### Fixed Effects\n")
  model_fe <- plm(formula, data=datos_model, index = c('iso2c', 'year'), model = "within")
  print(kable(tidy(model_fe) %>% mutate(significant = case_when(p.value < 0.001 ~ '***', 
                                                  p.value < 0.01  ~ '**',
                                                  p.value < 0.05  ~ '*',
                                                  p.value < 0.1   ~ '.',
                                                  TRUE            ~ ''))))
  
    cat("* R-Squared: ",r.squared(model_fe)," \n")
  
    cat("* Breusch-Pagan LM test - Cross Sectional Dependance \n")
    print(kable(tidy(pcdtest(model_fe, test = c("lm")))))
    
    cat("* Pesaran CD test - Cross Sectional Dependance \n")
    print(kable(tidy(pcdtest(model_fe, test = c("cd")))))
    
    cat("* Serial Correlation\n")
    print(kable(tidy(pbgtest(model_fe))))
    
    cat("* Robust covariance matrix estimation \n")
    print(kable(tidy(coeftest(model_fe, vcovHC(model_fe, method = 'arellano'))) %>% 
                  mutate(significant = case_when(p.value < 0.001 ~ '***', 
                                                  p.value < 0.01  ~ '**',
                                                  p.value < 0.05  ~ '*',
                                                  p.value < 0.1   ~ '.',
                                                  TRUE            ~ ''))))
    
  cat("##### Random Effects\n")
  model_re <- plm(formula, data=datos_model, index = c('iso2c', 'year'), model = "random")
  print(kable(tidy(model_re) %>% mutate(significant = case_when(p.value < 0.001 ~ '***', 
                                                  p.value < 0.01  ~ '**',
                                                  p.value < 0.05  ~ '*',
                                                  p.value < 0.1   ~ '.',
                                                  TRUE            ~ ''))))
  
    cat("* R-Squared: ",r.squared(model_re)," \n")
  
    cat("* Breusch-Pagan LM test - Cross Sectional Dependance \n")
    print(kable(tidy(pcdtest(model_re, test = c("lm")))))
    
    cat("* Pesaran CD test - Cross Sectional Dependance \n")
    print(kable(tidy(pcdtest(model_re, test = c("cd")))))
    
    cat("* Serial Correlation\n")
    print(kable(tidy(pbgtest(model_re))))
  
    cat("* Robust covariance matrix estimation \n")
    print(kable(tidy(coeftest(model_re, vcovHC(model_re, method = 'white1'))) %>% 
                  mutate(significant = case_when(p.value < 0.001 ~ '***', 
                                                  p.value < 0.01  ~ '**',
                                                  p.value < 0.05  ~ '*',
                                                  p.value < 0.1   ~ '.',
                                                  TRUE            ~ ''))))
    
  cat("##### Time-Fixed Effects\n")
  t_form <- paste(f$vd, '~ factor(year) +', paste(c(f$vint, f$vi, f$vf), collapse = ' + '))
  t_formula = as.formula(t_form)
  model_ft <- plm(t_formula, data=datos_model, index = c('iso2c', 'year'), model = "within")
  print(kable(tidy(model_ft) %>% mutate(significant = case_when(p.value < 0.001 ~ '***', 
                                                  p.value < 0.01  ~ '**',
                                                  p.value < 0.05  ~ '*',
                                                  p.value < 0.1   ~ '.',
                                                  TRUE            ~ ''))))
  
    cat("* R-Squared: ",r.squared(model_ft)," \n")
  
    cat("* Breusch-Pagan LM test - Cross Sectional Dependance \n")
    print(kable(tidy(pcdtest(model_ft, test = c("lm")))))
    
    cat("* Pesaran CD test - Cross Sectional Dependance \n")
    print(kable(tidy(pcdtest(model_ft, test = c("cd")))))
    
    cat("* Serial Correlation\n")
    print(kable(tidy(pbgtest(model_ft))))
    
    cat("* Robust covariance matrix estimation \n")
    print(kable(tidy(coeftest(model_ft, vcovHC(model_ft, method = 'arellano'))) %>% 
                  mutate(significant = case_when(p.value < 0.001 ~ '***', 
                                                  p.value < 0.01  ~ '**',
                                                  p.value < 0.05  ~ '*',
                                                  p.value < 0.1   ~ '.',
                                                  TRUE            ~ ''))))
    
  cat("##### Tests \n")
  
  cat("* Breusch Pagan Test (heteroskedasticity)\n")
  print(kable(tidy(bptest(formula, data = datos_model, studentize = F)) %>% 
                mutate(alternative = 'heteroskedasticity')))
  
  cat("* Variance Inflation Factors - multicollinearity  \n")
  print(kable(vif(model_ols)))
    
  cat("* Test for Fixed Effects\n")
  print(kable(tidy(pFtest(model_fe, model_ols))))
  
  cat("* Hausman Test\n")
  print(kable(tidy(phtest(model_fe, model_re))))
  
  cat("* Test for Time-Fixed Effects\n")
  print(kable(tidy(pFtest(model_ft, model_fe))))
  
  cat("##### Unit Root Test\n")
  for (i in c(f$vd, f$vi)) {
    cat("* ", i, "\n")
    y <- data.frame(split(datos_model[[i]], datos_model$iso2c)) # individuals in columns
    print(kable(tidy(purtest(y, pmax = 4, exo = "intercept", test = "madwu")$statistic)))
  }
  
  if (length(f$vint) == 1) {
    i <- strsplit(f$vint, split = "*", fixed = T)[[1]][1]
    cat("* ", i, "\n")
    y <- data.frame(split(datos_model[[i]], datos_model$iso2c)) # individuals in columns
    print(kable(tidy(purtest(y, pmax = 4, exo = "intercept", test = "madwu")$statistic)))
  }
}
```


```{r}
vif(model_ols)
```


```{r}
coeftest(model_ols)
coeftest(model_ols, vcovHC)
coeftest(model_re, vcovHC(model_re, type = "HC1"))
coeftest(model_re, vcovHC(model_re, method = 'white1'))

coeftest(model_fe, vcovHC(model_re, method = "arellano"))


```

